# Active Record 経由で、データベースに接続するために接続環境を設定
# （データベースへの接続設定）

# デフォルトの設定
# エイリアスである&で、配下のサブパラメーターに別名を付ける
default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

# 開発環境の設定
development:
  # エイリアスで別名を付けたブロックを * で参照し、挿入
  <<: *default
  database: db/development.sqlite3

# テスト環境の設定
test:
  <<: *default
  database: db/test.sqlite3

# 本番環境の設定
production:
  <<: *default
  database: db/production.sqlite3
